home/urls.py
from . import views
from django.urls import path


app_name = 'home'

urlpatterns = [
    path ('', views.index, name='index'),
]

project/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('accounts/', include('django.contrib.auth.urls')),
    path('accounts/', include('accounts.urls')),
    path('', include('home.urls')),
    path('trainee/', include('trainee.urls')),
    path('instructor/', include('instructor.urls')),
    path('track/', include('track.urls')),


]

track/urls.py
from . import views
from django.urls import path


app_name = 'track'

urlpatterns = [
    path ('', views.index, name='index'),
    # path ('add/', views.insert, name='insert'),
    path ('add/', views.insert, name='insert'), # For model Form action to add new track

    path ('delete/<int:id>', views.delete, name='delete'),
    path ('update/<int:id>', views.update, name='update'),

]

track/models.py
from django.db import models

# Create your models here.

class Track(models.Model):
    name = models.CharField(max_length=100)

    def __str__(self):
        return self.name

track/forms.py
from django import forms
from .models import *


class AddNewTrack(forms.ModelForm):
    class Meta:
        model = Track
        fields = '__all__'

track/views.py
from django.shortcuts import render, get_object_or_404
from django.contrib import messages
from django.contrib.auth.decorators import login_required
from django.http import HttpResponse, HttpResponseRedirect
from .models import Track
from .forms import AddNewTrack
# Create your views here.

@login_required
def index(request):
    all_tracks = Track.objects.all()
    return render(request, 'track/list.html', context={'all_tracks': all_tracks})

# Using model form

@login_required
def insert(request):
    if request.method == 'POST':
        track_name = AddNewTrack(request.POST)
        if track_name.is_valid():
            track_name.save()
            track_name = track_name.cleaned_data['name']
            messages.success(request, f'Track {track_name} added successfully.')
            return HttpResponseRedirect('/track/')  # Redirect to the index page
        else:
            messages.error(request, 'Track Name is required')  # Fixed typo here
    else:
        track_name = AddNewTrack()

    return render(request,'track/add.html', context={'form': AddNewTrack()})




# # Generic

# def insert(request):
#     if request.method == 'POST':
#         track_name = request.POST.get('name', None)

#         if track_name:
#             response = Track(
#                 name=track_name,
#             )
#             response.save()
#             messages.success(request, f'Track {track_name} added successfully.')
#             return HttpResponseRedirect('/track/')  # Redirect to the index page
#         else:
#             messages.error(request, 'Track Name is required')  # Fixed typo here

#     return render(request, 'track/add.html')

@login_required
def delete(request, id):
    Track.objects.filter(id=id).delete()
    return HttpResponseRedirect('/track/')  # Redirect to the index page

@login_required
def update(request, id):
    track = get_object_or_404(Track, pk=id)
    if request.method == 'POST':
        track.name = request.POST['name']
        track.save()
        return HttpResponseRedirect('/track/') # Redirect to the index page
    return render(request, 'track/update.html', {'track': track})

templates/track/add.html
{% extends 'base.html' %}
{% load static %}
{% block body %}
<div class="container-fluid pt-4 px-4">
    <div class="row g-4">
        <div class="col-sm-12 col-xl-12">
            <div class="bg-secondary rounded h-100 p-4">
                <h6 class="mb-4">Add Track Form</h6>
                <form method="POST">
                    {% csrf_token %}
                    {{ form.as_p}}
                    {% comment %} <div class="mb-3">
                        <label for="track_Name" class="form-label">Track Name</label>
                        <input type="text" class="form-control" name = "name" required />
                    </div> {% endcomment %}
                    <button type="submit" class="btn btn-primary">Add Track</button>
                </form>
            </div>
        </div>
    </div>
</div>
{% endblock body %}

templates/track/list.html
{% extends 'base.html' %}
{% load static %}
{% block body %}
    <div class="container-fluid pt-4 px-4">
        <div class="bg-secondary text-center rounded p-4">
            {% if messages %}
                <div class="alert alert-success">
                    {% for message in messages %}
                        {{ message }}
                    {% endfor %}
                </div>
            {% endif %}
            <div class="d-flex align-items-center justify-content-between mb-4">
                <h6 class="mb-0">All instructor</h6>
                <a class="btn btn-sm btn-primary" href="{% url 'track:insert'%}">Add Track</a>
            </div>
            <div class="table-responsive">
                <table class="table text-start align-middle table-bordered table-hover mb-0">
                    <thead>
                        <tr class="text-white">
                            <th scope="col">ID</th>
                            <th scope="col">Name</th>
                            <th scope="col">Actions</th>
                        </tr>
                    </thead>
                    <tbody>
                        {% for track in all_tracks %}
                        <tr>
                            <td>{{ track.id }}</td>
                            <td>{{ track.name }}</td>
                            <td>
                                <a class="btn btn-sm btn-primary" href="{% url 'track:update' track.id %}">Update</a>
                                <a class="btn btn-sm btn-primary" href="{% url 'track:delete' track.id %}">Delete</a>
                            </td>
                        </tr>
                        {% endfor %}
                    </tbody>
                </table>
            </div>
        </div>
    </div>
{% endblock body %}

templates/track/update.html
{% extends 'base.html' %}
{% load static %}
{% block body %}
<div class="container-fluid pt-4 px-4">
    <div class="row g-4">
        <div class="col-sm-12 col-xl-12">
            <div class="bg-secondary rounded h-100 p-4">
                <h6 class="mb-4">Update Track Form</h6>
                <form method="POST">
                    {% csrf_token %}
                    <div class="mb-3">
                        <label for="Instructor_Name" class="form-label">Track Name</label>
                        <input type="text" class="form-control" name="name" value="{{ track.name }}" required />
                    </div>
                    <button type="submit" class="btn btn-primary">Update Track</button>
                </form>
            </div>
        </div>
    </div>
</div>
{% endblock body %}