home/urls.py
from . import views
from django.urls import path


app_name = 'home'

urlpatterns = [
    path ('', views.index, name='index'),
]

instructor/urls.py
from . import views
from django.urls import path


app_name = 'instructor'

urlpatterns = [
    path ('', views.index, name='index'),
    path ('add/', views.insert, name='insert'),
    path ('delete/<int:id>', views.delete, name='delete'),
    path ('update/<int:id>', views.update, name='update'),

]

project/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('accounts/', include('django.contrib.auth.urls')),
    path('accounts/', include('accounts.urls')),
    path('', include('home.urls')),
    path('trainee/', include('trainee.urls')),
    path('instructor/', include('instructor.urls')),
    path('track/', include('track.urls')),


]

instructor/models.py
from django.db import models

# Create your models here.

class Instructor(models.Model):
    name = models.CharField(max_length=100)
    salary = models.IntegerField()
    bdate = models.DateField()



    def __str__(self):
        return self.name

instructor/views.py
from django.shortcuts import render, get_object_or_404
from django.contrib import messages
from django.contrib.auth.decorators import login_required
from django.http import HttpResponse, HttpResponseRedirect
from .models import Instructor
# Create your views here.


@login_required
def index(request):
    all_instructor = Instructor.objects.all()
    messages_list = messages.get_messages(request)
    context = {'all_instructor': all_instructor, 'messages': messages_list}
    # print(all_instructor)

    return render(request, 'instructor/list.html', context)

@login_required
def insert(request):
    if request.method == 'POST':
        instructor_name = request.POST.get('name', None)
        salary = request.POST.get('salary', None)
        instructor_date = request.POST.get('bdate', None)

        if instructor_name and salary and instructor_date:
            response = Instructor(
                name=instructor_name,
                salary=salary,
                bdate=instructor_date
            )
            response.save()
            messages.success(request, f'Instructor {instructor_name}added successfully.')
            return HttpResponseRedirect('/instructor/')  # Redirect to the index page
        else:
            messages.error(request, 'All fields (Name, Salary, and Instructor Date) are required')

    return render(request, 'instructor/add.html')

@login_required
def delete(request, id):
    Instructor.objects.filter(id=id).delete()
    return HttpResponseRedirect('/instructor/') # Redirect to the index page


@login_required
def update(request, id):
    instructor = get_object_or_404(Instructor, pk=id)
    if request.method == 'POST':
        instructor.name = request.POST['name']
        instructor.salary = request.POST['salary']
        instructor.bdate = request.POST['bdate']
        instructor.save()
        return HttpResponseRedirect('/instructor/') # Redirect to the index page
    return render(request, 'instructor/update.html', {'instructor': instructor})

templates/instructor/add.html
{% extends 'base.html' %}
{% load static %}
{% block body %}
<div class="container-fluid pt-4 px-4">
    <div class="row g-4">
        <div class="col-sm-12 col-xl-12">
            <div class="bg-secondary rounded h-100 p-4">
                <h6 class="mb-4">Add Instructor Form</h6>
                <form method="POST">
                    {% csrf_token %}
                    <div class="mb-3">
                        <label for="Instructor_Name" class="form-label">Instructor Name</label>
                        <input type="text" class="form-control" name="name" required />
                    </div>
                    <div class="mb-3">
                        <label for="Salary" class "form-label">Instructor Salary</label>
                        <input type="number" class="form-control" name="salary" />
                    </div>
                    <div class="mb-3">
                        <label for="Instructor_date" class="form-label">Instructor Birth Day</label>
                        <input type="date" class="form-control" name="bdate" />
                    </div>
                    <button type="submit" class="btn btn-primary">Add Instructor</button>
                </form>
            </div>
        </div>
    </div>
</div>
{% endblock body %}

templates/instructor/delete.html
{% extends 'base.html' %}
{% load static %}
{% block body %}
<h1> hello Delete of instuctor</h1>
{% endblock body %}

templates/instructor/list.html
{% extends 'base.html' %}
{% load static %}
{% block body %}
    <div class="container-fluid pt-4 px-4">
        <div class="bg-secondary text-center rounded p-4">
            {% if messages %}
                <div class="alert alert-success">
                    {% for message in messages %}
                        {{ message }}
                    {% endfor %}
                </div>
            {% endif %}
            <div class="d-flex align-items-center justify-content-between mb-4">
                <h6 class="mb-0">All instructor</h6>
                <a class="btn btn-sm btn-primary" href="{% url 'instructor:insert'%}">Add instructor</a>
            </div>
            <div class="table-responsive">
                <table class="table text-start align-middle table-bordered table-hover mb-0">
                    <thead>
                        <tr class="text-white">
                            <th scope="col">Name</th>
                            <th scope="col">Salary</th>
                            <th scope="col">Birth Day Date</th>
                            <th scope="col">Actions</th>
                        </tr>
                    </thead>
                    <tbody>
                        {% for instructor in all_instructor %}
                        <tr>
                            <td>{{ instructor.name }}</td>
                            <td>{{ instructor.salary }}</td>
                            <td>{{ instructor.bdate }}</td>
                            <td>
                                <a class="btn btn-sm btn-primary" href="{% url 'instructor:update' instructor.id %}">Update</a>
                                <a class="btn btn-sm btn-primary" href="{% url 'instructor:delete' instructor.id %}">Delete</a>
                            </td>
                        </tr>
                        {% endfor %}
                    </tbody>
                </table>
            </div>
        </div>
    </div>
{% endblock body %}

templates/instructor/update.html
{% extends 'base.html' %}
{% load static %}
{% block body %}
<div class="container-fluid pt-4 px-4">
    <div class="row g-4">
        <div class="col-sm-12 col-xl-12">
            <div class="bg-secondary rounded h-100 p-4">
                <h6 class="mb-4">Update Instructor Form</h6>
                <form method="POST">
                    {% csrf_token %}
                    <div class="mb-3">
                        <label for="Instructor_Name" class="form-label">Instructor Name</label>
                        <input type="text" class="form-control" name="name" value="{{ instructor.name }}" required />
                    </div>
                    <div class="mb-3">
                        <label for="Salary" class="form-label">Instructor Salary</label>
                        <input type="number" class="form-control" name="salary" value="{{ instructor.salary }}" />
                    </div>
                    <div class="mb-3">
                        <label for="Instructor_date" class="form-label">Instructor Birth Day</label>
                        <input type="date" class="form-control" name="bdate" value="{{ instructor.bdate }}" />
                    </div>
                    <button type="submit" class="btn btn-primary">Update Instructor</button>
                </form>
            </div>
        </div>
    </div>
</div>
{% endblock body %}