accounts/urls.py
from . import views
from django.urls import path

app_name = 'accounts'

urlpatterns = [
    path ('login/', views.login, name='login'),
    path ('signup/', views.signup, name='signup'),
    path ('profile/', views.profile, name='profile'),
    path('logout/', views.Logout, name="logout"),
    path ('profile/edit/', views.profile_edit, name='profile_edit'),


]

home/urls.py
from . import views
from django.urls import path


app_name = 'home'

urlpatterns = [
    path ('', views.index, name='index'),
]

instructor/urls.py
from . import views
from django.urls import path


app_name = 'instructor'

urlpatterns = [
    path ('', views.index, name='index'),
    path ('add/', views.insert, name='insert'),
    path ('delete/<int:id>', views.delete, name='delete'),
    path ('update/<int:id>', views.update, name='update'),

]

project/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('accounts/', include('django.contrib.auth.urls')),
    path('accounts/', include('accounts.urls')),
    path('', include('home.urls')),
    path('trainee/', include('trainee.urls')),
    path('instructor/', include('instructor.urls')),
    path('track/', include('track.urls')),


]

track/urls.py
from . import views
from django.urls import path


app_name = 'track'

urlpatterns = [
    path ('', views.index, name='index'),
    # path ('add/', views.insert, name='insert'),
    path ('add/', views.insert, name='insert'), # For model Form action to add new track

    path ('delete/<int:id>', views.delete, name='delete'),
    path ('update/<int:id>', views.update, name='update'),

]

trainee/urls.py
from . import views
from django.urls import path
from trainee.views import *


app_name = 'trainee'

urlpatterns = [
    path ('', views.list, name='list'),
    # path ('add/', views.insert, name='insert'),
    path ('add/',InsertTrainee.as_view(), name='insert'),
    path ('update/<int:id>/', views.update, name='update'),
    path ('delete/<int:id>/', views.delete, name='delete'),

]

templates/base.html
{% load static %}

<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="utf-8">
    <title>DarkPan - Bootstrap 5 Admin Template</title>
    <meta content="width=device-width, initial-scale=1.0" name="viewport">
    <meta content="" name="keywords">
    <meta content="" name="description">

    <!-- Favicon -->
    <link href="img/favicon.ico" rel="icon">

    <!-- Google Web Fonts -->
    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=Open+Sans:wght@400;600&family=Roboto:wght@500;700&display=swap" rel="stylesheet">

    <!-- Icon Font Stylesheet -->
    <link href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.10.0/css/all.min.css" rel="stylesheet">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.4.1/font/bootstrap-icons.css" rel="stylesheet">

    <!-- Libraries Stylesheet -->
    <link href="{% static 'lib/owlcarousel/assets/owl.carousel.min.css' %}" rel="stylesheet">
    <link href="{% static 'lib/tempusdominus/css/tempusdominus-bootstrap-4.min.css' %}" rel="stylesheet" />

    <!-- Customized Bootstrap Stylesheet -->
    <link href="{% static 'css/bootstrap.min.css' %}" rel="stylesheet">

    <!-- Template Stylesheet -->
    <link href="{% static 'css/style.css' %}" rel="stylesheet">
</head>

<body>
    <div class="container-fluid position-relative d-flex p-0">
        <!-- Sidebar Start -->
        <div class="sidebar pe-4 pb-3">
            <nav class="navbar bg-secondary navbar-dark">
                <a href="{% url 'home:index' %}" class="navbar-brand mx-4 mb-3">
                    <h3 class="text-primary"><i class="fa fa-user-edit me-2"></i>Dashboard</h3>
                </a>
                <div class="d-flex align-items-center ms-4 mb-4">
                    <div class="ms-3">
                        {% if request.user.is_authenticated %}
                        {% else %}
                            <h6 class="mb-0">{{request.user.username}}</h6>
                        {% endif %}
                    </div>
                </div>
                <div class="navbar-nav w-100">
                    <a href="{% url 'home:index' %}" class="nav-item nav-link active"><i class="fa fa-tachometer-alt me-2"></i>Dashboard</a>
                    <div class="nav-item dropdown">
                        <a href="#" class="nav-link dropdown-toggle" data-bs-toggle="dropdown"><i class="fa fa-laptop me-2"></i>Trainee</a>
                        <div class="dropdown-menu bg-transparent border-0">
                            <a href="{% url 'trainee:list' %}" class="dropdown-item">List Trainee</a>
                            <a href="{% url 'trainee:insert' %}" class="dropdown-item">add Trainee</a>
                        </div>
                    </div>
                    <div class="nav-item dropdown">
                        <a href="#" class="nav-link dropdown-toggle" data-bs-toggle="dropdown"><i class="fa fa-laptop me-2"></i>Instructor</a>
                        <div class="dropdown-menu bg-transparent border-0">
                            <a href="{% url 'instructor:index' %}" class="dropdown-item">List Instructor</a>
                            <a href="{% url 'instructor:insert' %}" class="dropdown-item">add Instructor</a>
                        </div>
                    </div>
                    <div class="nav-item dropdown">
                        <a href="#" class="nav-link dropdown-toggle" data-bs-toggle="dropdown"><i class="fa fa-laptop me-2"></i>Track</a>
                        <div class="dropdown-menu bg-transparent border-0">
                            <a href="{% url 'track:index' %}" class="dropdown-item">List Track</a>
                            <a href="{% url 'track:insert' %}" class="dropdown-item">add Track</a>
                        </div>
                    </div>
                </div>
            </nav>
        </div>
        <!-- Sidebar End -->
        <!-- Content Start -->
        <div class="content">
            <!-- Navbar Start -->
            <nav class="navbar navbar-expand bg-secondary navbar-dark sticky-top px-4 py-0">
                <div class="navbar-nav align-items-center ms-auto">

                    {% if request.user.is_authenticated %}
                    <div class="nav-item">
                        <a href="{% url 'accounts:profile' %}" class="nav-link">
                            Profile
                        </a>
                    </div>
                    {% else %}
                        <div class="nav-item">
                            <a href="{% url 'accounts:login' %}" class="nav-link">
                                Log In
                            </a>
                        </div>
                        <div class="nav-item">
                            <a href="{% url 'accounts:signup' %}" class="nav-link">
                                Sign Up
                            </a>
                        </div>
                    {% endif %}
                    <div class="nav-item dropdown">
                        <a href="#" class="nav-link dropdown-toggle" data-bs-toggle="dropdown">
                            <img class="rounded-circle me-lg-2" src="{% static 'img/user.jpg' %}" alt="" style="width: 40px; height: 40px;">
                            <span class="d-none d-lg-inline-flex">{{request.user.username}}</span>
                        </a>
                        <div class="dropdown-menu dropdown-menu-end bg-secondary border-0 rounded-0 rounded-bottom m-0">
                            <a href="{% url 'accounts:profile' %}" class="dropdown-item">My Profile</a>
                            <a href="{% url 'accounts:logout' %}" class="dropdown-item">Log Out</a>
                        </div>
                    </div>
                </div>
            </nav>
            <!-- Navbar End -->
            {% block body %}
            <!-- Sales Chart Start -->
            <div class="container-fluid pt-4 px-4">
                <div class="row g-4">
                    <div class="col-sm-12 col-xl-12">
                        <div class="bg-secondary text-center rounded p-4">
                            <div class="d-flex align-items-center justify-content-between mb-4">
                                <h6 class="mb-0">Worldwide Sales</h6>
                                <a href="">Show All</a>
                            </div>
                            <canvas id="worldwide-sales"></canvas>
                        </div>
                    </div>
                </div>
            </div>
            <!-- Sales Chart End -->

            {% endblock body %}

            <!-- Footer Start -->
            <div class="container-fluid pt-4 px-4">
                <div class="bg-secondary rounded-top p-4">
                    <div class="row">
                        <div class="col-12 col-sm-6 text-center text-sm-start">
                            &copy; <a href="#">Your Site Name</a>, All Right Reserved.
                        </div>
                        <div class="col-12 col-sm-6 text-center text-sm-end">
                            <!--/*** This template is free as long as you keep the footer author’s credit link/attribution link/backlink. If you'd like to use the template without the footer author’s credit link/attribution link/backlink, you can purchase the Credit Removal License from "https://htmlcodex.com/credit-removal". Thank you for your support. ***/-->
                            Designed By <a href="https://htmlcodex.com">HTML Codex</a>
                            <br>Distributed By: <a href="https://themewagon.com" target="_blank">ThemeWagon</a>
                        </div>
                    </div>
                </div>
            </div>
            <!-- Footer End -->
        </div>
        <!-- Content End -->


        <!-- Back to Top -->
        <a href="#" class="btn btn-lg btn-primary btn-lg-square back-to-top"><i class="bi bi-arrow-up"></i></a>
    </div>

    <!-- JavaScript Libraries -->
    <script src="https://code.jquery.com/jquery-3.4.1.min.js"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0/dist/js/bootstrap.bundle.min.js"></script>
    <script src="lib/chart/chart.min.js"></script>
    <script src="lib/easing/easing.min.js"></script>
    <script src="lib/waypoints/waypoints.min.js"></script>
    <script src="lib/owlcarousel/owl.carousel.min.js"></script>
    <script src="lib/tempusdominus/js/moment.min.js"></script>
    <script src="lib/tempusdominus/js/moment-timezone.min.js"></script>
    <script src="lib/tempusdominus/js/tempusdominus-bootstrap-4.min.js"></script>

    <!-- Template Javascript -->
    <script src="js/main.js"></script>
</body>

</html>

templates/inher_base.html
{% extends 'base.html' %}
{% load static %}
{% block body %}
<div class="container-fluid pt-4 px-4">
    <div class="row g-4">
        <div class="col-sm-12 col-xl-12">
            <div class="bg-secondary rounded h-100 p-4">
                {% block content %}

                {% endblock content %}
            </div>
        </div>
    </div>
</div>
{% endblock body%}