home/urls.py
from . import views
from django.urls import path


app_name = 'home'

urlpatterns = [
    path ('', views.index, name='index'),
]

project/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('accounts/', include('django.contrib.auth.urls')),
    path('accounts/', include('accounts.urls')),
    path('', include('home.urls')),
    path('trainee/', include('trainee.urls')),
    path('instructor/', include('instructor.urls')),
    path('track/', include('track.urls')),


]

trainee/urls.py
from . import views
from django.urls import path
from trainee.views import *


app_name = 'trainee'

urlpatterns = [
    path ('', views.list, name='list'),
    # path ('add/', views.insert, name='insert'),
    path ('add/',InsertTrainee.as_view(), name='insert'),
    path ('update/<int:id>/', views.update, name='update'),
    path ('delete/<int:id>/', views.delete, name='delete'),

]

trainee/models.py
from django.db import models
from track.models import Track
# Create your models here.

class Trainee(models.Model):
    name = models.CharField(max_length=200)
    bdate = models.DateField()
    track = models.ForeignKey(Track, on_delete=models.CASCADE)

trainee/forms.py
from django import forms
from django.core.exceptions import ValidationError
from trainee.models import Trainee
from track.models import Track
from datetime import date


class AddTraineeform(forms.Form):
    name = forms.CharField(required=True, max_length=100)
    bdate = forms.DateField(input_formats=['%Y-%d-%m'], help_text='YYYY-14-01')
    track = forms.ModelChoiceField(queryset=Track.objects.all())

trainee/views.py
from django.shortcuts import render, get_object_or_404
from django.http import HttpResponse, HttpResponseRedirect
from django.contrib.auth.decorators import login_required
from .models import *
from .forms import *
from django.contrib import messages
from django.views import View



@login_required
def list(request):
    all_trainees = Trainee.objects.all()
    return render(request, 'trainee/list.html', {'all_trainees': all_trainees})

@login_required
def delete(request, id):
    Trainee.objects.filter(id=id).delete()
    messages.success(request, 'Trainee deleted successfully.')
    return HttpResponseRedirect('/trainee/')

@login_required
def update(request, id):
    trainee = get_object_or_404(Trainee, pk=id)
    if request.method == 'POST':
        trainee.name = request.POST['name']
        trainee.bdate = request.POST['bdate']
        track_id = request.POST['track']
        track = Track.objects.get(pk=track_id)
        trainee.track = track  # Update the trainee's track field

        trainee.save()
        messages.success(request, f'Trainee {trainee.name} updated successfully.')
        return HttpResponseRedirect('/trainee/')
    return render(request, 'trainee/update.html', {'trainee': trainee,
                                                   'tracks': Track.objects.all()})


# def insert(request):
#     if request.method == 'POST':
#         name = request.POST['name']
#         bdate = request.POST['bdate']
#         track_id = request.POST['track']

#         track = Track.objects.get(pk=track_id)

#         Trainee.objects.create(name=name, track=track, bdate=bdate)

#         messages.success(request, f'Trainee {name} added successfully.')
#         return HttpResponseRedirect('/trainee/')
#     return render(request, 'trainee/add.html', {'tracks': Track.objects.all()})

class InsertTrainee(View):
    @login_required
    def get(self, request):
        return render(request, 'trainee/add.html', {'tracks': Track.objects.all(),
                                                    'form': AddTraineeform()})
    @login_required
    def post(self, request):
        # form = AddTraineeform(request.POST)
        # if form.is_valid():
        #     name = request.POST['name']
        #     bdate = request.POST['bdate']
        #     track_id = request.POST['track']
        #     track = Track.objects.get(pk=track_id)
        #     Trainee.objects.create(name=name, track=track, bdate=bdate)
        #     messages.success(request, f'Trainee {name} added successfully.')
        #     return HttpResponseRedirect('/trainee/')
        # else:
        #     return render(request, 'trainee/add.html', {'tracks': Track.objects.all(),
        #                                             'form': AddTraineeform(),
        #                                             'msg': form.errors})

        form = AddTraineeform(request.POST)  # Create a form instance with submitted data
        if form.is_valid():
            name = form.cleaned_data['name']
            track = form.cleaned_data['track']
            bdate = form.cleaned_data['bdate']
            track_id = request.POST['track']
            track = Track.objects.get(pk=track_id)
            Trainee.objects.create(name=name, track=track, bdate=bdate)

            if name:
                Trainee.objects.create(name=name, track=track, bdate=bdate)
                return HttpResponseRedirect('/trainee/')
            else:
                context = {'msg': 'You must enter the Trainee\'s name'}
        else:
            context = {'form': form}  # Send the form back with errors

        return render(request, 'trainee/add.html', context)

templates/trainee/add.html
{% extends 'base.html' %}
{% load static %}
{% block body %}
    <div class="container-fluid pt-4 px-4">
        <div class="row g-4">
            <div class="col-sm-12 col-xl-12">
                <div class="bg-secondary rounded h-100 p-4">
                    <h6 class="mb-4">Add Trainee Form from native</h6>
                    <form method="POST">
                        {% csrf_token %}
                        <div class="mb-3">
                            <label for="Trainee_Name" class="form-label">Trainee Name</label>
                            <input type="text" class="form-control" name="name" required />
                        </div>
                        <div class="mb-3">
                            <label for="track" class="form-label">Trainee Track</label>
                            <select class="form-control" name="track">
                                {% for track in tracks %}
                                    <option value="{{track.id}}">{{track.name}}</option>
                                {% endfor %}
                            </select>
                        </div>
                        <div class="mb-3">
                            <label for="Trainee_date" class="form-label">Trainee Birth Day</label>
                            <input type="date" class="form-control" name="bdate" />
                        </div>
                        <button type="submit" class="btn btn-primary">Add Trainee</button>
                    </form>
                </div>
            </div>
        </div>
    </div>
    <div class="container-fluid pt-4 px-4">
        <div class="row g-4">
            <div class="col-sm-12 col-xl-12">
                <div class="bg-secondary rounded h-100 p-4">
                    <h6 class="mb-4">Add Trainee Form django</h6>
                    <form method="POST">
                        {% csrf_token %}
                        {{ form.as_p }}
                        <button type="submit" class="btn btn-primary">Add Trainee</button>
                    </form>
                    <div class="">
                        <h1>{{msg}}</h1>
                    </div>
                </div>
            </div>
        </div>
    </div>
{% endblock body %}

templates/trainee/delete.html
{% extends 'base.html' %}
{% load static %}
{% block body %}
<h1> hello Delete of trainee</h1>
{% endblock body %}

templates/trainee/list.html
{% extends 'base.html' %}
{% load static %}
{% block body %}
    <div class="container-fluid pt-4 px-4">
        <div class="bg-secondary text-center rounded p-4">
            {% if messages %}
                <div class="alert alert-success">
                    {% for message in messages %}
                        {{ message }}
                    {% endfor %}
                </div>
            {% endif %}
            <div class="d-flex align-items-center justify-content-between mb-4">
                <h6 class="mb-0">Recent Salse</h6>
                <a class="btn btn-sm btn-primary" href="{% url 'trainee:insert'%}">Add trainee</a>
            </div>
            <div class="table-responsive">
                <table class="table text-start align-middle table-bordered table-hover mb-0">
                    <thead>
                        <tr class="text-white">
                            <th scope="col">name</th>
                            <th scope="col">birth day</th>
                            <th scope="col">track</th>
                        </tr>
                    </thead>
                    <tbody>
                        {% for trainee in all_trainees %}
                        <tr>
                            <td>{{ trainee.name }}</td>
                            <td>{{ trainee.bdate }}</td>
                            <td>{{ trainee.track }}</td>
                            <td>
                                <a class="btn btn-sm btn-primary" href="{% url 'trainee:update' trainee.id %}">Update</a>
                                <a class="btn btn-sm btn-primary" href="{% url 'trainee:delete' trainee.id %}">Delete</a>
                            </td>
                        </tr>
                        {% endfor %}
                    </tbody>
                </table>
            </div>
        </div>
    </div>
{% endblock body %}

templates/trainee/update.html
{% extends 'base.html' %}
{% load static %}
{% block body %}
<div class="container-fluid pt-4 px-4">
    <div class="row g-4">
        <div class="col-sm-12 col-xl-12">
            <div class="bg-secondary rounded h-100 p-4">
                <h6 class="mb-4">Update Trainee Form</h6>
                <form method="POST">
                    {% csrf_token %}
                    <div class="mb-3">
                        <label for="Instructor_Name" class="form-label">Trainee Name</label>
                        <input type="text" class="form-control" name="name" value="{{ trainee.name }}" required />
                    </div>
                    <div class="mb-3">
                        <label for="track" class="form-label">Trainee Track</label>
                        <select class="form-control" name="track">
                            {% for track in tracks %}
                                <option value="{{track.id}}">{{track.name}}</option>
                            {% endfor %}
                        </select>
                    </div>
                    <div class="mb-3">
                        <label for="Instructor_date" class="form-label">Trainee Birth Day</label>
                        <input type="date" class="form-control" name="bdate" value="{{ trainee.bdate }}" />
                    </div>
                    <button type="submit" class="btn btn-primary">Update Trainee</button>
                </form>
            </div>
        </div>
    </div>
</div>
{% endblock body %}